-- Archive pieces from The Met Open Access (CC0). Generated by scripts/build-archive-seed.mjs.

INSERT INTO artist (slug, name, status, life_dates, country_code, bio) VALUES
('rouff', 'Rouff', 'archive', 'French, 1844–1914', 'FR', 'Design House represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('lord-taylor', 'Lord & Taylor', 'archive', 'American, founded 1826', 'US', 'Department Store represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('s-gluck', 'S. Gluck', 'archive', NULL, NULL, 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('mrs-samuel-shimn', 'Mrs. Samuel Shimn', 'archive', NULL, NULL, 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('iida-co-takashimaya', 'Iida & Co./Takashimaya', 'archive', 'Japanese, founded 1831', 'JP', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('tuna-moosbrugger', 'Tuna & Moosbrugger', 'archive', NULL, NULL, 'Manufacturer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('mme-mantel', 'Mme. Mantel', 'archive', 'French', 'FR', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('mlle-louise', 'Mlle. Louise', 'archive', NULL, NULL, 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('jeffers-french-shoes', 'Jeffers French Shoes', 'archive', NULL, NULL, 'Retailer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('e-d-burt-co-fine-shoes', 'E.D. Burt & Co. Fine Shoes', 'archive', NULL, NULL, 'Department Store represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('thomas-ridout', 'Thomas Ridout', 'archive', 'British', 'GB', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('hattat-freres', 'Hattat Frères', 'archive', NULL, 'FR', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('a-antinori', 'A. Antinori', 'archive', 'Italian', 'IT', 'Department Store represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('jacob-ulrich-holfeldt-tostrup', 'Jacob Ulrich Holfeldt Tostrup', 'archive', 'Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)', NULL, 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('eugene-fontenay', 'Eugêne Fontenay', 'archive', 'French, 1823–1887', 'FR', 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('castellani', 'Castellani', 'archive', NULL, NULL, 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('dumoret', 'Dumoret', 'archive', 'French', 'FR', 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('carlo-giuliano', 'Carlo Giuliano', 'archive', 'Italian, active England, ca. 1831–1895', 'IT', 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('maison-rouvenat-of-paris', 'Maison Rouvenat of Paris', 'archive', NULL, NULL, 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('tiffany-co', 'Tiffany & Co.', 'archive', 'American, New York, NY, 1837–present', 'US', 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('unger-brothers', 'Unger Brothers', 'archive', '1872–1919', NULL, 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('calima-yotoco-artist', 'Calima (Yotoco) artist', 'archive', NULL, NULL, 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('chimu-artist-s', 'Chimú artist(s)', 'archive', NULL, NULL, 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('nasca-artist-s', 'Nasca artist(s)', 'archive', NULL, NULL, 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('house-of-worth', 'House of Worth', 'archive', 'French, 1858–1956', 'FR', 'Design House represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('charles-frederick-worth', 'Charles Frederick Worth', 'archive', 'French (born England), Bourne 1825–1895 Paris', 'FR', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('emile-pingat', 'Emile Pingat', 'archive', 'French, 1820–1901', 'FR', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('maison-pingat', 'Maison Pingat', 'archive', 'French', 'FR', 'Design House represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('l-p-hollander-co', 'L.P. Hollander & Co.', 'archive', 'American', 'US', 'Department Store represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('m-a-connelly', 'M. A. Connelly', 'archive', 'American (born Ireland), County Cork 1834–1958 New York', 'US', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('h-o-hanlon', 'H. O. Hanlon', 'archive', 'American', 'US', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('balch-price-company', 'Balch, Price & Company', 'archive', 'American, founded 1869', 'US', 'Department Store represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('debillemont', 'Debillemont', 'archive', NULL, NULL, 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('donaldson-brothers', 'Donaldson Brothers', 'archive', 'American, New York', 'US', 'Designer represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('b-a-of-spain', 'B. A. (of Spain)', 'archive', NULL, NULL, 'Maker represented in the costume and decorative arts collections of The Metropolitan Museum of Art.'),
('luigi-saulini', 'Luigi Saulini', 'archive', 'Italian, 1819–1883', 'IT', 'Artist represented in the costume and decorative arts collections of The Metropolitan Museum of Art.')
ON CONFLICT (slug) DO NOTHING;

-- Evening dress (Rouff), Met 157153
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-dress-rouff-157153', ar.id, t.id, 'Evening dress', 'ca. 1895', 1893, 'Evening dress in silk, metal, by Rouff (French, 1844–1914), dated ca. 1895. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/157153', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. William E. S. Griswold, 1941'
FROM artist ar, artwork_type t WHERE ar.slug = 'rouff' AND t.name = 'Evening dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-dress-rouff-157153' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-dress-rouff-157153' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-157153.webp', 'photo', 'Evening dress, Rouff', 'The Metropolitan Museum of Art', 'CC0', 1185, 1750
FROM artwork WHERE slug = 'evening-dress-rouff-157153';

-- Evening dress (Lord & Taylor), Met 158114
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-dress-lord-taylor-158114', ar.id, t.id, 'Evening dress', '1900–1902', 1900, 'Evening dress in silk, linen, by Lord & Taylor (American, founded 1826), dated 1900–1902. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/158114', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Caroline A. Ward, 1959'
FROM artist ar, artwork_type t WHERE ar.slug = 'lord-taylor' AND t.name = 'Evening dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-dress-lord-taylor-158114' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-dress-lord-taylor-158114' AND m.name = 'Linen';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-dress-lord-taylor-158114' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-158114.webp', 'photo', 'Evening dress, Lord & Taylor', 'The Metropolitan Museum of Art', 'CC0', 1313, 1750
FROM artwork WHERE slug = 'evening-dress-lord-taylor-158114';

-- Ensemble (S. Gluck), Met 155743
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'ensemble-s-gluck-155743', ar.id, t.id, 'Ensemble', '1900–1905', 1900, 'Ensemble in silk, by S. Gluck, dated 1900–1905. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/155743', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. J. W. Post, 1944'
FROM artist ar, artwork_type t WHERE ar.slug = 's-gluck' AND t.name = 'Ensemble';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ensemble-s-gluck-155743' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'ensemble-s-gluck-155743' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-155743.webp', 'photo', 'Ensemble, S. Gluck', 'The Metropolitan Museum of Art', 'CC0', 1024, 1750
FROM artwork WHERE slug = 'ensemble-s-gluck-155743';

-- Ensemble (Mrs. Samuel Shimn), Met 157544
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'ensemble-mrs-samuel-shimn-157544', ar.id, t.id, 'Ensemble', '1888', 1888, 'Ensemble in cotton, linen, silk, by Mrs. Samuel Shimn, dated 1888. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/157544', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. Samuel Shimn, 1928'
FROM artist ar, artwork_type t WHERE ar.slug = 'mrs-samuel-shimn' AND t.name = 'Ensemble';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ensemble-mrs-samuel-shimn-157544' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ensemble-mrs-samuel-shimn-157544' AND m.name = 'Cotton';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ensemble-mrs-samuel-shimn-157544' AND m.name = 'Linen';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'ensemble-mrs-samuel-shimn-157544' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-157544.webp', 'photo', 'Ensemble, Mrs. Samuel Shimn', 'The Metropolitan Museum of Art', 'CC0', 1122, 1750
FROM artwork WHERE slug = 'ensemble-mrs-samuel-shimn-157544';

-- Coat (Iida & Co./Takashimaya), Met 83924
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'coat-iida-co-takashimaya-83924', ar.id, t.id, 'Coat', 'ca. 1900', 1895, 'Coat in silk, by Iida & Co./Takashimaya (Japanese, founded 1831), dated ca. 1900. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'Japanese',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/83924', 'Gift of Joseph L. Brotherton, 1985'
FROM artist ar, artwork_type t WHERE ar.slug = 'iida-co-takashimaya' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'coat-iida-co-takashimaya-83924' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'coat-iida-co-takashimaya-83924' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-83924.webp', 'photo', 'Coat, Iida & Co./Takashimaya', 'The Metropolitan Museum of Art', 'CC0', 1400, 1750
FROM artwork WHERE slug = 'coat-iida-co-takashimaya-83924';

-- Coat (Tuna & Moosbrugger), Met 157336
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'coat-tuna-moosbrugger-157336', ar.id, t.id, 'Coat', '1890', 1890, 'Coat in wool, by Tuna & Moosbrugger, dated 1890. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/157336', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Florence R. Le Sauvage, 1962'
FROM artist ar, artwork_type t WHERE ar.slug = 'tuna-moosbrugger' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'coat-tuna-moosbrugger-157336' AND m.name = 'Wool';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'coat-tuna-moosbrugger-157336' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-157336.webp', 'photo', 'Coat, Tuna & Moosbrugger', 'The Metropolitan Museum of Art', 'CC0', 960, 1750
FROM artwork WHERE slug = 'coat-tuna-moosbrugger-157336';

-- Hat (Mme. Mantel), Met 156128
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'hat-mme-mantel-156128', ar.id, t.id, 'Hat', 'ca. 1885', 1883, 'Hat in fur, wool, silk, by Mme. Mantel (French), dated ca. 1885. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156128', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the Princess Viggo in accordance with the wishes of the Misses Hewitt, 1931'
FROM artist ar, artwork_type t WHERE ar.slug = 'mme-mantel' AND t.name = 'Hat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mme-mantel-156128' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mme-mantel-156128' AND m.name = 'Wool';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mme-mantel-156128' AND m.name = 'Fur';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'hat-mme-mantel-156128' AND te.name = 'Millinery';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156128.webp', 'photo', 'Hat, Mme. Mantel', 'The Metropolitan Museum of Art', 'CC0', 1400, 1572
FROM artwork WHERE slug = 'hat-mme-mantel-156128';

-- Hat (Mlle. Louise), Met 156529
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'hat-mlle-louise-156529', ar.id, t.id, 'Hat', 'ca. 1890', 1888, 'Hat in bast fiber, cotton, birds, feathers, by Mlle. Louise, dated ca. 1890. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156529', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Pratt Institute, 1943'
FROM artist ar, artwork_type t WHERE ar.slug = 'mlle-louise' AND t.name = 'Hat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mlle-louise-156529' AND m.name = 'Cotton';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mlle-louise-156529' AND m.name = 'Feathers';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'hat-mlle-louise-156529' AND m.name = 'Straw';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'hat-mlle-louise-156529' AND te.name = 'Millinery';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156529.webp', 'photo', 'Hat, Mlle. Louise', 'The Metropolitan Museum of Art', 'CC0', 1400, 1224
FROM artwork WHERE slug = 'hat-mlle-louise-156529';

-- Shoes (Jeffers French Shoes), Met 168730
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'shoes-jeffers-french-shoes-168730', ar.id, t.id, 'Shoes', '1866', 1866, 'Shoes in leather, by Jeffers French Shoes, dated 1866. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/168730', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Harriette Yeaton, 1947'
FROM artist ar, artwork_type t WHERE ar.slug = 'jeffers-french-shoes' AND t.name = 'Shoes';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'shoes-jeffers-french-shoes-168730' AND m.name = 'Leather';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-168730.webp', 'photo', 'Shoes, Jeffers French Shoes', 'The Metropolitan Museum of Art', 'CC0', 1400, 822
FROM artwork WHERE slug = 'shoes-jeffers-french-shoes-168730';

-- Slippers (E.D. Burt & Co. Fine Shoes), Met 156241
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'slippers-e-d-burt-co-fine-shoes-156241', ar.id, t.id, 'Slippers', '1865–85', 1865, 'Slippers in silk, metal, by E.D. Burt & Co. Fine Shoes, dated 1865–85. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156241', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Beulah Stevenson, 1958'
FROM artist ar, artwork_type t WHERE ar.slug = 'e-d-burt-co-fine-shoes' AND t.name = 'Shoes';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'slippers-e-d-burt-co-fine-shoes-156241' AND m.name = 'Silk';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156241.webp', 'photo', 'Slippers, E.D. Burt & Co. Fine Shoes', 'The Metropolitan Museum of Art', 'CC0', 1400, 871
FROM artwork WHERE slug = 'slippers-e-d-burt-co-fine-shoes-156241';

-- Shoes (Thomas Ridout), Met 156118
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'shoes-thomas-ridout-156118', ar.id, t.id, 'Shoes', '1750–70', 1750, 'Shoes in silk, by Thomas Ridout (British), dated 1750–70. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'British',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156118', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Charles Blaney, 1926'
FROM artist ar, artwork_type t WHERE ar.slug = 'thomas-ridout' AND t.name = 'Shoes';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'shoes-thomas-ridout-156118' AND m.name = 'Silk';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156118.webp', 'photo', 'Shoes, Thomas Ridout', 'The Metropolitan Museum of Art', 'CC0', 1400, 697
FROM artwork WHERE slug = 'shoes-thomas-ridout-156118';

-- Shoes (Hattat Frères), Met 157878
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'shoes-hattat-freres-157878', ar.id, t.id, 'Shoes', 'ca. 1880', 1878, 'Shoes in silk, by Hattat Frères, dated ca. 1880. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/157878', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Edith J. Evans, 1929'
FROM artist ar, artwork_type t WHERE ar.slug = 'hattat-freres' AND t.name = 'Shoes';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'shoes-hattat-freres-157878' AND m.name = 'Silk';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-157878.webp', 'photo', 'Shoes, Hattat Frères', 'The Metropolitan Museum of Art', 'CC0', 1400, 976
FROM artwork WHERE slug = 'shoes-hattat-freres-157878';

-- Bag (A. Antinori), Met 156837
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bag-a-antinori-156837', ar.id, t.id, 'Bag', 'first quarter 19th century', 1800, 'Bag in leather, by A. Antinori (Italian), dated first quarter 19th century. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'Italian',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156837', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. Alvah E. Reed, 1965'
FROM artist ar, artwork_type t WHERE ar.slug = 'a-antinori' AND t.name = 'Bag';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bag-a-antinori-156837' AND m.name = 'Leather';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156837.webp', 'photo', 'Bag, A. Antinori', 'The Metropolitan Museum of Art', 'CC0', 1063, 1750
FROM artwork WHERE slug = 'bag-a-antinori-156837';

-- Necklace (Jacob Ulrich Holfeldt Tostrup), Met 189038
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'necklace-jacob-ulrich-holfeldt-tostrup-189038', ar.id, t.id, 'Necklace', 'ca. 1873', 1868, 'Necklace in silver filigree, by Jacob Ulrich Holfeldt Tostrup (Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)), dated ca. 1873. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/189038', 'Gift of Mrs. Harriette M. Arnold, 1906'
FROM artist ar, artwork_type t WHERE ar.slug = 'jacob-ulrich-holfeldt-tostrup' AND t.name = 'Necklace';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'necklace-jacob-ulrich-holfeldt-tostrup-189038' AND m.name = 'Silver';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'necklace-jacob-ulrich-holfeldt-tostrup-189038' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-189038.webp', 'photo', 'Necklace, Jacob Ulrich Holfeldt Tostrup', 'The Metropolitan Museum of Art', 'CC0', 1400, 1172
FROM artwork WHERE slug = 'necklace-jacob-ulrich-holfeldt-tostrup-189038';

-- Necklace (Eugêne Fontenay), Met 207698
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'necklace-eugene-fontenay-207698', ar.id, t.id, 'Necklace', 'ca. 1870', 1865, 'Necklace in gold, enamel and diamonds, by Eugêne Fontenay (French, 1823–1887), dated ca. 1870. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/207698', 'Gift of Dorothy Burr Thompson, 1987'
FROM artist ar, artwork_type t WHERE ar.slug = 'eugene-fontenay' AND t.name = 'Necklace';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'necklace-eugene-fontenay-207698' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'necklace-eugene-fontenay-207698' AND m.name = 'Enamel';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'necklace-eugene-fontenay-207698' AND m.name = 'Diamonds';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'necklace-eugene-fontenay-207698' AND te.name = 'Enamelling';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'necklace-eugene-fontenay-207698' AND te.name = 'Stone setting';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 3 FROM artwork a, technique te WHERE a.slug = 'necklace-eugene-fontenay-207698' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-207698.webp', 'photo', 'Necklace, Eugêne Fontenay', 'The Metropolitan Museum of Art', 'CC0', 1400, 1750
FROM artwork WHERE slug = 'necklace-eugene-fontenay-207698';

-- Archaeological revival necklace (Castellani), Met 716657
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'archaeological-revival-necklace-castellani-716657', ar.id, t.id, 'Archaeological revival necklace', 'ca. 1880', 1875, 'Necklace in gold, glass, by Castellani, dated ca. 1880. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/716657', 'Gift of Jacqueline Loewe Fowler, in honor of Stephanie Fowler Levin and Clay Fowler, 2016'
FROM artist ar, artwork_type t WHERE ar.slug = 'castellani' AND t.name = 'Necklace';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'archaeological-revival-necklace-castellani-716657' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'archaeological-revival-necklace-castellani-716657' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'archaeological-revival-necklace-castellani-716657' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-716657.webp', 'photo', 'Archaeological revival necklace, Castellani', 'The Metropolitan Museum of Art', 'CC0', 1400, 1202
FROM artwork WHERE slug = 'archaeological-revival-necklace-castellani-716657';

-- Brooch (Jacob Ulrich Holfeldt Tostrup), Met 189051
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-jacob-ulrich-holfeldt-tostrup-189051', ar.id, t.id, 'Brooch', 'ca. 1873', 1868, 'Brooch in silver filigree, by Jacob Ulrich Holfeldt Tostrup (Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)), dated ca. 1873. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/189051', 'Gift of Mrs. Harriette M. Arnold, 1906'
FROM artist ar, artwork_type t WHERE ar.slug = 'jacob-ulrich-holfeldt-tostrup' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-jacob-ulrich-holfeldt-tostrup-189051' AND m.name = 'Silver';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-jacob-ulrich-holfeldt-tostrup-189051' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-189051.webp', 'photo', 'Brooch, Jacob Ulrich Holfeldt Tostrup', 'The Metropolitan Museum of Art', 'CC0', 1400, 1172
FROM artwork WHERE slug = 'brooch-jacob-ulrich-holfeldt-tostrup-189051';

-- Brooch (Dumoret), Met 199756
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-dumoret-199756', ar.id, t.id, 'Brooch', 'ca. 1850–70', 1845, 'Brooch in gold, diamonds, crystal, silk, by Dumoret (French), dated ca. 1850–70. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/199756', 'Gift of Mrs. Alfred Schermerhorn, in memory of Mrs. John Gerard Coster, 1946'
FROM artist ar, artwork_type t WHERE ar.slug = 'dumoret' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-dumoret-199756' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-dumoret-199756' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-dumoret-199756' AND m.name = 'Diamonds';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-dumoret-199756' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-dumoret-199756' AND te.name = 'Stone setting';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'brooch-dumoret-199756' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-199756.webp', 'photo', 'Brooch, Dumoret', 'The Metropolitan Museum of Art', 'CC0', 1400, 1377
FROM artwork WHERE slug = 'brooch-dumoret-199756';

-- Brooch (Carlo Giuliano), Met 236770
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-carlo-giuliano-236770', ar.id, t.id, 'Brooch', 'before 1896', 1800, 'Brooch in gold, glass, by Carlo Giuliano (Italian, active England, ca. 1831–1895), dated before 1896. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/236770', 'Gift of Judith H. Siegel, 2014'
FROM artist ar, artwork_type t WHERE ar.slug = 'carlo-giuliano' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-carlo-giuliano-236770' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-carlo-giuliano-236770' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-carlo-giuliano-236770' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-236770.webp', 'photo', 'Brooch, Carlo Giuliano', 'The Metropolitan Museum of Art', 'CC0', 1400, 1006
FROM artwork WHERE slug = 'brooch-carlo-giuliano-236770';

-- Brooch (Maison Rouvenat of Paris), Met 199806
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-maison-rouvenat-of-paris-199806', ar.id, t.id, 'Brooch', 'ca. 1867', 1862, 'Brooch in gold, enamel, diamonds, by Maison Rouvenat of Paris, dated ca. 1867. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/199806', 'Bequest of Xenophon Leonidas Mavroidi, 1946'
FROM artist ar, artwork_type t WHERE ar.slug = 'maison-rouvenat-of-paris' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND m.name = 'Enamel';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND m.name = 'Diamonds';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND te.name = 'Enamelling';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND te.name = 'Stone setting';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 3 FROM artwork a, technique te WHERE a.slug = 'brooch-maison-rouvenat-of-paris-199806' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-199806.webp', 'photo', 'Brooch, Maison Rouvenat of Paris', 'The Metropolitan Museum of Art', 'CC0', 1400, 1410
FROM artwork WHERE slug = 'brooch-maison-rouvenat-of-paris-199806';

-- Brooch (Tiffany & Co.), Met 1025
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-tiffany-co-1025', ar.id, t.id, 'Brooch', 'ca. 1900', 1897, 'Brooch in emerald, diamonds, platinum, by Tiffany & Co. (American, New York, NY, 1837–present), dated ca. 1900. From the collection of The Metropolitan Museum of Art (The American Wing).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/1025', 'Gift of Susan Dwight Bliss, 1953'
FROM artist ar, artwork_type t WHERE ar.slug = 'tiffany-co' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-tiffany-co-1025' AND m.name = 'Diamonds';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-tiffany-co-1025' AND m.name = 'Gemstones';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-tiffany-co-1025' AND te.name = 'Stone setting';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-1025.webp', 'photo', 'Brooch, Tiffany & Co.', 'The Metropolitan Museum of Art', 'CC0', 1400, 1750
FROM artwork WHERE slug = 'brooch-tiffany-co-1025';

-- Brooch (Tiffany & Co.), Met 16805
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-tiffany-co-16805', ar.id, t.id, 'Brooch', '1868', 1868, 'Brooch in gold, pearls, black enamel, and hair, by Tiffany & Co. (American, New York, NY, 1837–present), dated 1868. From the collection of The Metropolitan Museum of Art (The American Wing).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/16805', 'Purchase, Susan and Jon Rotenstreich Gift, 2000'
FROM artist ar, artwork_type t WHERE ar.slug = 'tiffany-co' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-tiffany-co-16805' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-tiffany-co-16805' AND m.name = 'Enamel';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-tiffany-co-16805' AND m.name = 'Pearls';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-tiffany-co-16805' AND te.name = 'Enamelling';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'brooch-tiffany-co-16805' AND te.name = 'Stone setting';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 3 FROM artwork a, technique te WHERE a.slug = 'brooch-tiffany-co-16805' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-16805.webp', 'photo', 'Brooch, Tiffany & Co.', 'The Metropolitan Museum of Art', 'CC0', 1400, 1543
FROM artwork WHERE slug = 'brooch-tiffany-co-16805';

-- Brooch (Unger Brothers), Met 1027
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'brooch-unger-brothers-1027', ar.id, t.id, 'Brooch', 'ca. 1900', 1900, 'Brooch in silver, by Unger Brothers (1872–1919), dated ca. 1900. From the collection of The Metropolitan Museum of Art (The American Wing).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/1027', 'Gift of Ronald S. Kane, 1967'
FROM artist ar, artwork_type t WHERE ar.slug = 'unger-brothers' AND t.name = 'Brooch';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'brooch-unger-brothers-1027' AND m.name = 'Silver';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'brooch-unger-brothers-1027' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-1027.webp', 'photo', 'Brooch, Unger Brothers', 'The Metropolitan Museum of Art', 'CC0', 1400, 1731
FROM artwork WHERE slug = 'brooch-unger-brothers-1027';

-- Bracelet (Castellani), Met 827209
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bracelet-castellani-827209', ar.id, t.id, 'Bracelet', 'ca. 1860', 1855, 'Bracelet in gold, by Castellani, dated ca. 1860. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/827209', 'Gift of Jacqueline Loewe Fowler, 2020'
FROM artist ar, artwork_type t WHERE ar.slug = 'castellani' AND t.name = 'Bracelet';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bracelet-castellani-827209' AND m.name = 'Gold';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'bracelet-castellani-827209' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-827209.webp', 'photo', 'Bracelet, Castellani', 'The Metropolitan Museum of Art', 'CC0', 1400, 659
FROM artwork WHERE slug = 'bracelet-castellani-827209';

-- Bracelet (Jacob Ulrich Holfeldt Tostrup), Met 189049
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bracelet-jacob-ulrich-holfeldt-tostrup-189049', ar.id, t.id, 'Bracelet', 'ca. 1873', 1868, 'Bracelet in silver filigree, by Jacob Ulrich Holfeldt Tostrup (Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)), dated ca. 1873. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/189049', 'Gift of Mrs. Harriette M. Arnold, 1906'
FROM artist ar, artwork_type t WHERE ar.slug = 'jacob-ulrich-holfeldt-tostrup' AND t.name = 'Bracelet';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bracelet-jacob-ulrich-holfeldt-tostrup-189049' AND m.name = 'Silver';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'bracelet-jacob-ulrich-holfeldt-tostrup-189049' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-189049.webp', 'photo', 'Bracelet, Jacob Ulrich Holfeldt Tostrup', 'The Metropolitan Museum of Art', 'CC0', 1400, 1172
FROM artwork WHERE slug = 'bracelet-jacob-ulrich-holfeldt-tostrup-189049';

-- Bracelet (Castellani), Met 236768
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bracelet-castellani-236768', ar.id, t.id, 'Bracelet', 'ca. 1860', 1855, 'Bracelet in gold, hardstone, by Castellani, dated ca. 1860. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/236768', 'Gift of Judith H. Siegel, 2014'
FROM artist ar, artwork_type t WHERE ar.slug = 'castellani' AND t.name = 'Bracelet';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bracelet-castellani-236768' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bracelet-castellani-236768' AND m.name = 'Gemstones';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'bracelet-castellani-236768' AND te.name = 'Stone setting';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'bracelet-castellani-236768' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-236768.webp', 'photo', 'Bracelet, Castellani', 'The Metropolitan Museum of Art', 'CC0', 1400, 1058
FROM artwork WHERE slug = 'bracelet-castellani-236768';

-- Headdress ornament (Calima (Yotoco) artist), Met 309411
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'headdress-ornament-calima-yotoco-artist-309411', ar.id, t.id, 'Headdress ornament', '100 BCE–700 CE', -100, 'Headdress ornament in gold, by Calima (Yotoco) artist, dated 100 BCE–700 CE. From the collection of The Metropolitan Museum of Art (The Michael C. Rockefeller Wing).', 'Calima (Yotoco)',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/309411', 'Gift and Bequest of Alice K. Bache, 1966, 1977'
FROM artist ar, artwork_type t WHERE ar.slug = 'calima-yotoco-artist' AND t.name = 'Headdress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'headdress-ornament-calima-yotoco-artist-309411' AND m.name = 'Gold';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-309411.webp', 'photo', 'Headdress ornament, Calima (Yotoco) artist', 'The Metropolitan Museum of Art', 'CC0', 1400, 1025
FROM artwork WHERE slug = 'headdress-ornament-calima-yotoco-artist-309411';

-- Feathered Headdress (Chimú artist(s)), Met 310463
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'feathered-headdress-chimu-artist-s-310463', ar.id, t.id, 'Feathered Headdress', '15th–early 17th century', 1400, 'Headdress in feathers, cotton, rope, by Chimú artist(s), dated 15th–early 17th century. From the collection of The Metropolitan Museum of Art (The Michael C. Rockefeller Wing).', 'Chimú',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/310463', 'The Michael C. Rockefeller Memorial Collection, Purchase, Nelson A. Rockefeller Gift, 1955'
FROM artist ar, artwork_type t WHERE ar.slug = 'chimu-artist-s' AND t.name = 'Headdress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'feathered-headdress-chimu-artist-s-310463' AND m.name = 'Cotton';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'feathered-headdress-chimu-artist-s-310463' AND m.name = 'Feathers';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'feathered-headdress-chimu-artist-s-310463' AND te.name = 'Millinery';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-310463.webp', 'photo', 'Feathered Headdress, Chimú artist(s)', 'The Metropolitan Museum of Art', 'CC0', 1245, 1750
FROM artwork WHERE slug = 'feathered-headdress-chimu-artist-s-310463';

-- Headdress ornament (Nasca artist(s)), Met 313008
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'headdress-ornament-nasca-artist-s-313008', ar.id, t.id, 'Headdress ornament', '1–700 CE', 1, 'Ornament in gold, by Nasca artist(s), dated 1–700 CE. From the collection of The Metropolitan Museum of Art (The Michael C. Rockefeller Wing).', 'Nasca',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/313008', 'The Michael C. Rockefeller Memorial Collection, Bequest of Nelson A. Rockefeller, 1979'
FROM artist ar, artwork_type t WHERE ar.slug = 'nasca-artist-s' AND t.name = 'Headdress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'headdress-ornament-nasca-artist-s-313008' AND m.name = 'Gold';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-313008.webp', 'photo', 'Headdress ornament, Nasca artist(s)', 'The Metropolitan Museum of Art', 'CC0', 1302, 1750
FROM artwork WHERE slug = 'headdress-ornament-nasca-artist-s-313008';

-- Evening coat (House of Worth), Met 159193
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-coat-house-of-worth-159193', ar.id, t.id, 'Evening coat', '1901', 1901, 'Evening coat in silk, fur: European polecat (Mustela putorius), by House of Worth (French, 1858–1956), dated 1901. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159193', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Edith Gardiner, 1926'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-coat-house-of-worth-159193' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-coat-house-of-worth-159193' AND m.name = 'Fur';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-coat-house-of-worth-159193' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159193.webp', 'photo', 'Evening coat, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1313, 1750
FROM artwork WHERE slug = 'evening-coat-house-of-worth-159193';

-- Evening coat (House of Worth), Met 159526
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-coat-house-of-worth-159526', ar.id, t.id, 'Evening coat', 'ca. 1900', 1898, 'Evening coat in silk, by House of Worth (French, 1858–1956), dated ca. 1900. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159526', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. William E. S. Griswold, 1941'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-coat-house-of-worth-159526' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-coat-house-of-worth-159526' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159526.webp', 'photo', 'Evening coat, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1204, 1750
FROM artwork WHERE slug = 'evening-coat-house-of-worth-159526';

-- Ball gown (House of Worth), Met 155944
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'ball-gown-house-of-worth-155944', ar.id, t.id, 'Ball gown', '1900', 1900, 'Ball gown in silk, rhinestones, by House of Worth (French, 1858–1956), dated 1900. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/155944', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the estate of Mrs. Arthur F. Schermerhorn, 1957'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Evening dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ball-gown-house-of-worth-155944' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'ball-gown-house-of-worth-155944' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'ball-gown-house-of-worth-155944' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-155944.webp', 'photo', 'Ball gown, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1115, 1750
FROM artwork WHERE slug = 'ball-gown-house-of-worth-155944';

-- Walking suit (House of Worth), Met 159303
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'walking-suit-house-of-worth-159303', ar.id, t.id, 'Walking suit', 'ca. 1889', 1888, 'Walking suit in silk, by House of Worth (French, 1858–1956), dated ca. 1889. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159303', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the Princess Viggo in accordance with the wishes of the Misses Hewitt, 1931'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Ensemble';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'walking-suit-house-of-worth-159303' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'walking-suit-house-of-worth-159303' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159303.webp', 'photo', 'Walking suit, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1210, 1750
FROM artwork WHERE slug = 'walking-suit-house-of-worth-159303';

-- Dinner dress (House of Worth), Met 159433
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'dinner-dress-house-of-worth-159433', ar.id, t.id, 'Dinner dress', '1897–1900', 1897, 'Dinner dress in silk, linen, by House of Worth (French, 1858–1956), dated 1897–1900. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159433', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. Ferris J. Meigs, 1961'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dinner-dress-house-of-worth-159433' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dinner-dress-house-of-worth-159433' AND m.name = 'Linen';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'dinner-dress-house-of-worth-159433' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159433.webp', 'photo', 'Dinner dress, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1116, 1750
FROM artwork WHERE slug = 'dinner-dress-house-of-worth-159433';

-- Afternoon jacket (House of Worth), Met 159315
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'afternoon-jacket-house-of-worth-159315', ar.id, t.id, 'Afternoon jacket', '1895', 1895, 'Afternoon jacket in silk, beads, by House of Worth (French, 1858–1956), dated 1895. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159315', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the Princess Viggo in accordance with the wishes of the Misses Hewitt, 1931'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Jacket';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'afternoon-jacket-house-of-worth-159315' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'afternoon-jacket-house-of-worth-159315' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'afternoon-jacket-house-of-worth-159315' AND te.name = 'Beadwork';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'afternoon-jacket-house-of-worth-159315' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159315.webp', 'photo', 'Afternoon jacket, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1400, 1641
FROM artwork WHERE slug = 'afternoon-jacket-house-of-worth-159315';

-- Evening ensemble (Charles Frederick Worth), Met 155770
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-ensemble-charles-frederick-worth-155770', ar.id, t.id, 'Evening ensemble', '1887', 1887, 'Evening ensemble in silk, metal, by Charles Frederick Worth (French (born England), Bourne 1825–1895 Paris), dated 1887. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/155770', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Edith Gardiner, 1926'
FROM artist ar, artwork_type t WHERE ar.slug = 'charles-frederick-worth' AND t.name = 'Ensemble';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-ensemble-charles-frederick-worth-155770' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-ensemble-charles-frederick-worth-155770' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-155770.webp', 'photo', 'Evening ensemble, Charles Frederick Worth', 'The Metropolitan Museum of Art', 'CC0', 1286, 1750
FROM artwork WHERE slug = 'evening-ensemble-charles-frederick-worth-155770';

-- Evening dress (House of Worth), Met 159187
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-dress-house-of-worth-159187', ar.id, t.id, 'Evening dress', 'ca. 1882', 1880, 'Evening dress in silk, by House of Worth (French, 1858–1956), dated ca. 1882. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159187', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the Princess Viggo in accordance with the wishes of the Misses Hewitt, 1931'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Evening dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-dress-house-of-worth-159187' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-dress-house-of-worth-159187' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159187.webp', 'photo', 'Evening dress, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1357, 1750
FROM artwork WHERE slug = 'evening-dress-house-of-worth-159187';

-- Evening jacket (House of Worth), Met 159304
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-jacket-house-of-worth-159304', ar.id, t.id, 'Evening jacket', 'ca. 1890', 1888, 'Evening jacket in silk, jet, linen, by House of Worth (French, 1858–1956), dated ca. 1890. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159304', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of the Princess Viggo in accordance with the wishes of the Misses Hewitt, 1931'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Jacket';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-jacket-house-of-worth-159304' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-jacket-house-of-worth-159304' AND m.name = 'Linen';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-jacket-house-of-worth-159304' AND m.name = 'Gemstones';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-jacket-house-of-worth-159304' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159304.webp', 'photo', 'Evening jacket, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1270, 1750
FROM artwork WHERE slug = 'evening-jacket-house-of-worth-159304';

-- Dolman (Emile Pingat), Met 159717
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'dolman-emile-pingat-159717', ar.id, t.id, 'Dolman', '1880s', 1880, 'Dolman in silk, linen, by Emile Pingat (French, 1820–1901), dated 1880s. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159717', 'Gift of Christopher Scholz and Ines Elskop, 2010'
FROM artist ar, artwork_type t WHERE ar.slug = 'emile-pingat' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dolman-emile-pingat-159717' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dolman-emile-pingat-159717' AND m.name = 'Linen';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'dolman-emile-pingat-159717' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159717.webp', 'photo', 'Dolman, Emile Pingat', 'The Metropolitan Museum of Art', 'CC0', 651, 1527
FROM artwork WHERE slug = 'dolman-emile-pingat-159717';

-- Evening cape (Maison Pingat), Met 156122
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-cape-maison-pingat-156122', ar.id, t.id, 'Evening cape', 'ca. 1891', 1889, 'Evening cape in wool, silk, fur, beads, by Maison Pingat (French), dated ca. 1891. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156122', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Marion Litchfield, 1950'
FROM artist ar, artwork_type t WHERE ar.slug = 'maison-pingat' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-cape-maison-pingat-156122' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-cape-maison-pingat-156122' AND m.name = 'Wool';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-cape-maison-pingat-156122' AND m.name = 'Fur';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-cape-maison-pingat-156122' AND m.name = 'Glass beads';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-cape-maison-pingat-156122' AND te.name = 'Beadwork';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 2 FROM artwork a, technique te WHERE a.slug = 'evening-cape-maison-pingat-156122' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156122.webp', 'photo', 'Evening cape, Maison Pingat', 'The Metropolitan Museum of Art', 'CC0', 1149, 1750
FROM artwork WHERE slug = 'evening-cape-maison-pingat-156122';

-- Evening cloak (Maison Pingat), Met 159020
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'evening-cloak-maison-pingat-159020', ar.id, t.id, 'Evening cloak', '1885–89', 1885, 'Evening cloak in silk, metal, by Maison Pingat (French), dated 1885–89. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/159020', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Anonymous Gift, in memory of Mrs. John Roebling, 1970'
FROM artist ar, artwork_type t WHERE ar.slug = 'maison-pingat' AND t.name = 'Coat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'evening-cloak-maison-pingat-159020' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'evening-cloak-maison-pingat-159020' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-159020.webp', 'photo', 'Evening cloak, Maison Pingat', 'The Metropolitan Museum of Art', 'CC0', 1130, 1750
FROM artwork WHERE slug = 'evening-cloak-maison-pingat-159020';

-- Dress (L.P. Hollander & Co.), Met 82633
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'dress-l-p-hollander-co-82633', ar.id, t.id, 'Dress', 'ca. 1885', 1880, 'Dress in silk, by L.P. Hollander & Co. (American), dated ca. 1885. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/82633', 'Gift of Miss Alexandra Francesca, 1955'
FROM artist ar, artwork_type t WHERE ar.slug = 'l-p-hollander-co' AND t.name = 'Dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dress-l-p-hollander-co-82633' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'dress-l-p-hollander-co-82633' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-82633.webp', 'photo', 'Dress, L.P. Hollander & Co.', 'The Metropolitan Museum of Art', 'CC0', 914, 1750
FROM artwork WHERE slug = 'dress-l-p-hollander-co-82633';

-- Dress (M. A. Connelly), Met 82627
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'dress-m-a-connelly-82627', ar.id, t.id, 'Dress', '1882–86', 1882, 'Dress in silk, by M. A. Connelly (American (born Ireland), County Cork 1834–1958 New York), dated 1882–86. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/82627', 'Gift of Mrs. Vanderbilt Webb, 1939'
FROM artist ar, artwork_type t WHERE ar.slug = 'm-a-connelly' AND t.name = 'Dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dress-m-a-connelly-82627' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'dress-m-a-connelly-82627' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-82627.webp', 'photo', 'Dress, M. A. Connelly', 'The Metropolitan Museum of Art', 'CC0', 969, 1750
FROM artwork WHERE slug = 'dress-m-a-connelly-82627';

-- Dress (House of Worth), Met 105336
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'dress-house-of-worth-105336', ar.id, t.id, 'Dress', '1883–85', 1883, 'Dress in silk, by House of Worth (French, 1858–1956), dated 1883–85. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/105336', 'Gift of Mr. and Mrs. Leonard Shepley, 1953'
FROM artist ar, artwork_type t WHERE ar.slug = 'house-of-worth' AND t.name = 'Dress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'dress-house-of-worth-105336' AND m.name = 'Silk';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'dress-house-of-worth-105336' AND te.name = 'Sewing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-105336.webp', 'photo', 'Dress, House of Worth', 'The Metropolitan Museum of Art', 'CC0', 1371, 1750
FROM artwork WHERE slug = 'dress-house-of-worth-105336';

-- Bonnet (H. O. Hanlon), Met 156880
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bonnet-h-o-hanlon-156880', ar.id, t.id, 'Bonnet', 'ca. 1887', 1885, 'Bonnet in straw, silk, cotton, metal, by H. O. Hanlon (American), dated ca. 1887. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156880', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Amelia Beard Hollenback, 1966'
FROM artist ar, artwork_type t WHERE ar.slug = 'h-o-hanlon' AND t.name = 'Hat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bonnet-h-o-hanlon-156880' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bonnet-h-o-hanlon-156880' AND m.name = 'Cotton';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bonnet-h-o-hanlon-156880' AND m.name = 'Straw';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'bonnet-h-o-hanlon-156880' AND te.name = 'Millinery';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156880.webp', 'photo', 'Bonnet, H. O. Hanlon', 'The Metropolitan Museum of Art', 'CC0', 1253, 1750
FROM artwork WHERE slug = 'bonnet-h-o-hanlon-156880';

-- Bonnet (Balch, Price & Company), Met 156157
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'bonnet-balch-price-company-156157', ar.id, t.id, 'Bonnet', 'ca. 1880', 1878, 'Bonnet in straw, silk, by Balch, Price & Company (American, founded 1869), dated ca. 1880. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156157', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of Mrs. James McF. Baker, 1948'
FROM artist ar, artwork_type t WHERE ar.slug = 'balch-price-company' AND t.name = 'Hat';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bonnet-balch-price-company-156157' AND m.name = 'Silk';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'bonnet-balch-price-company-156157' AND m.name = 'Straw';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'bonnet-balch-price-company-156157' AND te.name = 'Millinery';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156157.webp', 'photo', 'Bonnet, Balch, Price & Company', 'The Metropolitan Museum of Art', 'CC0', 1390, 1750
FROM artwork WHERE slug = 'bonnet-balch-price-company-156157';

-- Fan (Debillemont), Met 156567
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'fan-debillemont-156567', ar.id, t.id, 'Fan', 'fourth quarter 19th century', 1876, 'Fan in mother-of-pearl, paper, gouache, metal, glass, by Debillemont, dated fourth quarter 19th century. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'French',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/156567', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Gift of George Arents in memory of Annie Walter Arents, 1949'
FROM artist ar, artwork_type t WHERE ar.slug = 'debillemont' AND t.name = 'Fan';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'fan-debillemont-156567' AND m.name = 'Glass beads';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'fan-debillemont-156567' AND m.name = 'Shell';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-156567.webp', 'photo', 'Fan, Debillemont', 'The Metropolitan Museum of Art', 'CC0', 1400, 826
FROM artwork WHERE slug = 'fan-debillemont-156567';

-- Fan (Donaldson Brothers), Met 157041
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'fan-donaldson-brothers-157041', ar.id, t.id, 'Fan', '1880', 1880, 'Fan in wood, paper, metal, by Donaldson Brothers (American, New York), dated 1880. From the collection of The Metropolitan Museum of Art (Costume Institute).', 'American',
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/157041', 'Brooklyn Museum Costume Collection at The Metropolitan Museum of Art, Gift of the Brooklyn Museum, 2009; Designated Purchase Fund, 1993'
FROM artist ar, artwork_type t WHERE ar.slug = 'donaldson-brothers' AND t.name = 'Fan';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-157041.webp', 'photo', 'Fan, Donaldson Brothers', 'The Metropolitan Museum of Art', 'CC0', 1400, 869
FROM artwork WHERE slug = 'fan-donaldson-brothers-157041';

-- Pair of earrings (B. A. (of Spain)), Met 206855
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'pair-of-earrings-b-a-of-spain-206855', ar.id, t.id, 'Pair of earrings', '19th century', 1800, 'Earrings in gold, jacinths (?), by B. A. (of Spain), dated 19th century. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/206855', 'Gift of Marguerite McBey, 1980'
FROM artist ar, artwork_type t WHERE ar.slug = 'b-a-of-spain' AND t.name = 'Earrings';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'pair-of-earrings-b-a-of-spain-206855' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'pair-of-earrings-b-a-of-spain-206855' AND m.name = 'Gemstones';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'pair-of-earrings-b-a-of-spain-206855' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-206855.webp', 'photo', 'Pair of earrings, B. A. (of Spain)', 'The Metropolitan Museum of Art', 'CC0', 1327, 1750
FROM artwork WHERE slug = 'pair-of-earrings-b-a-of-spain-206855';

-- Earring (Jacob Ulrich Holfeldt Tostrup), Met 189053
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'earring-jacob-ulrich-holfeldt-tostrup-189053', ar.id, t.id, 'Earring', 'ca. 1873', 1868, 'Earring in silver filigree, by Jacob Ulrich Holfeldt Tostrup (Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)), dated ca. 1873. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/189053', 'Gift of Mrs. Harriette M. Arnold, 1906'
FROM artist ar, artwork_type t WHERE ar.slug = 'jacob-ulrich-holfeldt-tostrup' AND t.name = 'Earrings';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'earring-jacob-ulrich-holfeldt-tostrup-189053' AND m.name = 'Silver';
INSERT INTO artwork_technique (artwork_id, technique_id, step_order) SELECT a.id, te.id, 1 FROM artwork a, technique te WHERE a.slug = 'earring-jacob-ulrich-holfeldt-tostrup-189053' AND te.name = 'Goldsmithing';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-189053.webp', 'photo', 'Earring, Jacob Ulrich Holfeldt Tostrup', 'The Metropolitan Museum of Art', 'CC0', 1400, 1172
FROM artwork WHERE slug = 'earring-jacob-ulrich-holfeldt-tostrup-189053';

-- Tiara (Jacob Ulrich Holfeldt Tostrup), Met 189050
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'tiara-jacob-ulrich-holfeldt-tostrup-189050', ar.id, t.id, 'Tiara', 'ca. 1873', 1868, 'Tiara in silver filigree, by Jacob Ulrich Holfeldt Tostrup (Norwegian, Sande, near Stavanger 1806–1890 Christiana (now Oslo)), dated ca. 1873. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/189050', 'Gift of Mrs. Harriette M. Arnold, 1906'
FROM artist ar, artwork_type t WHERE ar.slug = 'jacob-ulrich-holfeldt-tostrup' AND t.name = 'Headdress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'tiara-jacob-ulrich-holfeldt-tostrup-189050' AND m.name = 'Silver';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-189050.webp', 'photo', 'Tiara, Jacob Ulrich Holfeldt Tostrup', 'The Metropolitan Museum of Art', 'CC0', 1400, 783
FROM artwork WHERE slug = 'tiara-jacob-ulrich-holfeldt-tostrup-189050';

-- Parure: tiara, necklace, and brooch (Luigi Saulini), Met 198636
INSERT INTO artwork (slug, artist_id, artwork_type_id, title, date_label, year, description, culture, source_name, source_url, credit_line)
SELECT 'parure-tiara-necklace-and-brooch-luigi-saulini-198636', ar.id, t.id, 'Parure: tiara, necklace, and brooch', 'mid-19th century', 1830, 'Parure in onyx and gold,, by Luigi Saulini (Italian, 1819–1883), dated mid-19th century. From the collection of The Metropolitan Museum of Art (European Sculpture and Decorative Arts).', NULL,
  'The Metropolitan Museum of Art', 'https://www.metmuseum.org/art/collection/search/198636', 'The Milton Weil Collection, 1940'
FROM artist ar, artwork_type t WHERE ar.slug = 'luigi-saulini' AND t.name = 'Headdress';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'parure-tiara-necklace-and-brooch-luigi-saulini-198636' AND m.name = 'Gold';
INSERT INTO artwork_material (artwork_id, material_id) SELECT a.id, m.id FROM artwork a, material m WHERE a.slug = 'parure-tiara-necklace-and-brooch-luigi-saulini-198636' AND m.name = 'Gemstones';
INSERT INTO media (artwork_id, file_url, media_type, caption, credit, license, width, height)
SELECT id, '/images/archive/met-198636.webp', 'photo', 'Parure: tiara, necklace, and brooch, Luigi Saulini', 'The Metropolitan Museum of Art', 'CC0', 1252, 1750
FROM artwork WHERE slug = 'parure-tiara-necklace-and-brooch-luigi-saulini-198636';

REFRESH MATERIALIZED VIEW artwork_search;
